services:
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SQL_INIT_MODE: ${SQL_INIT_MODE}
      JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
      JPA_HIBERNATE_DIALECT: ${JPA_HIBERNATE_DIALECT}
